name: Build Conduit

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ 8 ]

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1.4.2
        with:
          java-version: ${{ matrix.java }}

      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Patch Conduit
        run: |
          git config --global user.email "ci@github.com"
          git config --global user.name "Github CI"
          git submodule update --init --recursive
          chmod +x ./conduit
          chmod -R +x scripts
          ./conduit jar
      
      - run: |
          mv conduit-paperclip.jar conduit-${{ github.run_number }}.jar
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.1.4
        with:
          name: conduit-JDK${{ matrix.java }}.jar
          path: conduit-${{ github.run_number }}.jar
          if-no-files-found: error
